[build]
  command = "npm run build"
  publish = "dist"

[functions]
  included_files = ["node_modules/pdfjs-dist/legacy/build/pdf.worker.mjs"]

[[redirects]]
  from = "https://scotuspdf.netlify.app/*"
  to = "https://scotuspdf.com/:splat"
  status = 301
  force = true
